FROM node:19.4.0-alpine AS builder
WORKDIR /frontend
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx:1.23.3-alpine
WORKDIR /usr/share/nginx/html
COPY --from=builder /frontend/build .
