version: '3.8'

services:
  frontend:
    image: frontend-dev-image
    build:
      dockerfile: Dockerfile.dev
    container_name: frontend-dev-container
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules/
    ports:
        - '3000:3000'
    environment:
        - NODE_ENV=development

  backend:
    image: backend-dev-image
    build:
      dockerfile: Dockerfile.dev
    container_name: backend-dev-container
    volumes:
      - ./backend:/var/www/html

volumes:
  node_modules:
