version: '3.8'

services:
  frontend:
    build:
      context: ./frontend

  backend:
    build:
      context: ./backend
    ports:
      - '1010:80'

  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ColocountDB
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - APACHE_PORT=8000
    ports:
      - '8000:8000'
