version: '3.8'

services:
  frontend:
    image: frontend-prod-image
    build:
      dockerfile: Dockerfile.prod
    container_name: frontend-prod-container
    ports:
      - '8080:80'
    environment:
      - NODE_ENV=production

  backend:
    image: backend-prod-image
    build:
      dockerfile: Dockerfile.prod
    container_name: backend-prod-container
