FROM php:8.1.2-apache
COPY --from=composer:2.5.1 /usr/bin/composer /usr/local/bin/composer
RUN docker-php-ext-install mysqli pdo pdo_mysql \
    && a2enmod rewrite
WORKDIR /var/www/html
COPY . .
RUN composer dump-autoload
